const REGEX = {
	DISPLAY_NAME: /^[A-Za-z][A-Za-z _-]*$/,
	DIGITS: /\d/,
};

const LIMITS = {
	DISPLAY_NAME_MAX: 30,
	PASSWORD_MIN: 8,
	PASSWORD_MAX: 200,
	PLAYER_NAME_MAX: 100,
	GRID_MIN: 3,
	GRID_MAX: 20,
	PLAYERS_MIN: 2,
	PLAYERS_MAX: 4,
	PRIVATE_ROOM_PLAYERS_MAX: 8,
	LIST_DEFAULT: 20,
	LIST_MAX: 100,
	SAFETY_BREAK: 2000,
	MAX_CONNECTIONS: 1000,
	MAX_CONNECTIONS_PER_IP: 20,
	MAX_ROOMS: 250,
	MAX_QUEUE_SIZE: 50,
} as const;

enum GAME_MODES {
	CASUAL = "casual",
	RANKED = "ranked",
}

const SCORING_POINTS = {
	WIN: 3,
	LOSS: 1,
} as const;

const RECONNECT_GRACE_MS = 30_000;
const ROOM_IDLE_TTL_MS = 300_000; // 5 minutes

const WS_RATE_LIMIT_WINDOW_MS = 60_000;
const WS_RATE_LIMIT_MAX_PER_IP = 120; // 120 messages per minute per IP
const WS_GLOBAL_MSG_BUDGET = 2000; // 2000 messages per minute globally
const WS_MAX_PAYLOAD_BYTES = 16 * 1024; // 16 KB
const WS_PING_INTERVAL_MS = 30_000;
const WS_IDLE_TIMEOUT_MS = 600_000; // 10 minutes

const RANKED_VELOCITY_LIMIT = 10;
const RANKED_VELOCITY_WINDOW_MS = 600_000; // 10 minutes

export {
	REGEX,
	LIMITS,
	GAME_MODES,
	SCORING_POINTS,
	RECONNECT_GRACE_MS,
	ROOM_IDLE_TTL_MS,
	WS_RATE_LIMIT_WINDOW_MS,
	WS_RATE_LIMIT_MAX_PER_IP,
	WS_GLOBAL_MSG_BUDGET,
	WS_MAX_PAYLOAD_BYTES,
	WS_PING_INTERVAL_MS,
	WS_IDLE_TIMEOUT_MS,
	RANKED_VELOCITY_LIMIT,
	RANKED_VELOCITY_WINDOW_MS,
};
